[package]
name = "sro-toolbox-infrastructure"
description = "Adapters implementing the toolbox's ports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sro-toolbox-application = { workspace = true }
sro-toolbox-domain = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
